# Header
menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/tommy351
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-4910098-7
favicon:
twitter: tommy351
google_plus: 108777679171675250079
fb_admins: 100000247608790
fb_app_id: